version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: paysecure-postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payuser
      POSTGRES_PASSWORD: paypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: paysecure-api:v2
    container_name: paysecure-api
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: payments
      DB_USER: payuser
      DB_PASSWORD: paypass
    ports:
      - "9000:9000"

volumes:
  postgres_data: